services:
  arangodb:
    image: arangodb/arangodb:3.11.8
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
      encryption-keyfile: db-secret
    volumes:
      - ~/grabit:/var/lib/arangodb3
  